server:
  port: 8100
#  context-path: /order_create_service
spring:
  application:
    name: order_create_service
  datasource:
    url: jdbc:mysql://10.10.10.37:3306/logistics_order?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cloudlinkscm.loms.service.order_create.domain.entity
  type-handlers-package: com.cloudlinkscm.loms.service.order_create.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    database-id: test
eureka:
  instance:
    hostname: 10.10.10.36
  client:
    enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
logging:
  file: ${spring.application.name}
  level:
    ROOT: info
    org.springframework: info
    org.springframework.web.servlet.view: info
    org.springframework.web.servlet.mvc: info
    com.cloudlinkscm: info
    com.zaxxer.hikari: ORDER

gateway-config:
   gateway: http://10.10.10.36:5555

hercules:
  debug: false
  dateFormatPattern: yyyy-MM-dd HH:mm:ss



