server:
  port: 8084
  #context-path: /customer_service
spring:
  application:
    name: customer_service
  datasource:
    url: jdbc:mysql://10.10.10.77:3306/archiver?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cloudlinkscm.loms.service.customer.domain.entity
  type-handlers-package: com.cloudlinkscm.loms.service.customer.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    database-id: test
eureka:
  instance:
    hostname: 10.10.10.76
  client:
    enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true

gateway-config:
   gateway: http://10.10.10.76:5555


hercules:
  debug: false
  dateFormatPattern: yyyy-MM-dd HH:mm:ss



